export const fieldTexts = {
    lang: { english: 'Language<span title="Refresh for changes">🔄</span>', hungarian: 'Nyelv<span title="Frissíts a változásokhoz">🔄</span>' },
    langSection: { english: 'Utilities', hungarian: 'Hasznosságok' },
    noAfk: { english: 'Never AFK', hungarian: 'Sosem AFK' },
    noPromo: { english: 'No Promotions', hungarian: 'Promóciók kikapcsolása' },
    skipDisliked: { english: 'Skip Disliked Songs', hungarian: 'Nem kedvelt dalok kihagyása' },
    padding: { english: 'Fix Layout<span title="Refresh for changes">🔄</span>', hungarian: 'Elrendezés javítása<span title="Frissíts a változásokhoz">🔄</span>' },
    extraButtons: { english: 'Extra Playback Buttons', hungarian: 'Több Irányító Gomb' },
    bg: { english: 'Change Background', hungarian: 'Háttér megváltoztatása' },
    bgSection: { english: 'Background Settings', hungarian: 'Háttér beállítások' },
    bgColor: { english: 'Background Color', hungarian: 'Háttérszín' },
    bgEnableGradient: { english: 'Enable Gradient', hungarian: 'Háttér színátmenet engedélyezése' },
    bgGradient: { english: 'Background Gradient Color', hungarian: 'Háttér színátmenet' },
    clock: { english: 'Change "Upgrade" Button', hungarian: '"Bővítés" Gomb Cserélése' },
    clockSection: { english: 'Upgrade Button', hungarian: 'Bővítés Gomb' },
    clockColor: { english: 'Clock Color', hungarian: 'Óra Színe' },
    clockGradient: { english: 'Enable Gradient', hungarian: 'Színátmenet Engedélyezése' },
    clockGradientColor: { english: 'Gradient Color', hungarian: 'Színátmenet' },
    visualizerPlace: { english: 'Visualizer Place', hungarian: 'Vizualizáló Helye' },
    visualizerPlaceSection: { english: 'Music Visualizer', hungarian: 'Zene Vizualizáló' },
    visualizerStartsFrom: { english: 'Visualizer Starts from', hungarian: 'Vizualizáló innen kezdődik:' },
    visualizerStartsFromOptions: { english: ['Left', 'Center', 'Right', 'Edges'], hungarian: ['Bal', 'Közép', 'Jobb', 'Szélek'] },
    visualizerColor: { english: 'Visualizer Color', hungarian: 'Vizualizáló Színe' },
    visualizerRgbEnabled: { english: 'RGB Mode', hungarian: 'RGB Mód' },
    visualizerFade: { english: 'Enable Bar Fade', hungarian: 'Sávok Áttűnésének Engedélyezése' },
    visualizerFft: { english: 'Bar Amount<span title="High values can affect performance and can break circle visualizer.">⚠️</span>', hungarian: 'Sáv mennyiség<span title="A magas értékek befolyásolhatják a teljesítményt és hibát okozhatnak a kör vizualizálóban.">⚠️</span>' },
    visualizerCircleEnabled: { english: 'Enable (Album Cover Only)', hungarian: 'Engedélyez (Csak Album Borítón)' },
    visualizerCircleEnabledSection: { english: 'Circle Visualizer', hungarian: 'Kör Vizualizáló' },
    visualizerRotate: { english: 'Rotation', hungarian: 'Forgás' },
    visualizerRotateDirection: { english: 'Rotation Direction', hungarian: 'Forgásirány' },
    visualizerMove: { english: 'Bars Movement Direction', hungarian: 'Sávok Mozgásiránya' },
    visualizerBassBounceEnabled: { english: 'Bass Bounce', hungarian: 'Basszusugrálás' },
    visualizerBassBounceSmooth: { english: 'Smooth Bounce', hungarian: 'Ugrálás Simítása' },
    visualizerImageType: { english: 'Image', hungarian: 'Kép' },
    visualizerImageRemoveThumbnail: { english: 'Remove Thumbnail', hungarian: 'Miniatűr Eltávolítása' },
    visualizerImageCustomURL: { english: 'Custom image URL', hungarian: 'Saját kép URL' },
    attention1: { english: 'Changes here can cause glitches!', hungarian: 'Az itteni változtatások hibákat okozhatnak!' },
    attention1Section: { english: 'Advanced Visualizer Settings', hungarian: 'Speciális Vizualizáló Beállítások' },
    visualizerRgbRed: { english: 'RGB:Red Value', hungarian: 'RGB:Piros Érték' },
    visualizerRgbGreen: { english: 'RGB:Green Value', hungarian: 'RGB:Zöld Érték' },
    visualizerRgbBlue: { english: 'RGB:Blue Value', hungarian: 'RGB:Kék Érték' },
    visualizerRgbSamples: { english: 'RGB:Samples', hungarian: 'RGB:Minták' },
    visualizerMinDecibels: { english: 'Min Decibels', hungarian: 'Min Decibel' },
    visualizerMaxDecibels: { english: 'Max Decibels', hungarian: 'Max Decibel' },
    visualizerSmoothing: { english: 'Smoothing Time Constant', hungarian: 'Simítási időállandó' },
    visualizerCutOff: { english: 'AudioData End Cutoff', hungarian: 'AudioData Vég Levágás' },
    visualizerBassBounceSensitivityStart: { english: 'Bass Bounce Sensitivity Start', hungarian: 'Basszusugrálás Érzékenység Kezdőérték' },
    visualizerBassBounceSensitivityEnd: { english: 'Bass Bounce Sensitivity End', hungarian: 'Basszusugrálás Érzékenység Végérték' },
    visualizerBassBounceDebug: { english: 'Bass Bounce Debug Color', hungarian: 'Basszusugrálás Debug Szín' },
};